config/routes.rb
OnPrem::Application.routes.draw do

  resources :pages

  resources :schools

  resources :slides

  resources :people

  resources :projects

  resources :users, only: :index

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks"}

  root to: "pages#home"

  match '/home' => 'pages#home'
  match '/offerings' => 'pages#offerings'
  match '/work' => 'pages#work'
  match '/team' => 'pages#team'
  match '/careers' => 'pages#careers'
  match '/contact' => 'pages#contact'
  match '/idc' => 'pages#idc'
  match '/about' => 'pages#about'
  
  

end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id         :integer          not null, primary key
#  first_name :string(255)
#  last_name  :string(255)
#  bio        :string(255)
#  linkedin   :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  title      :string(255)
#  phone      :string(255)
#  twitter    :string(255)
#  github     :string(255)
#  portrait   :string(255)
#

class Person < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :bio, :linkedin, :email, :title, :school_ids, :phone, :twitter, :github, :portrait
  has_and_belongs_to_many :schools

  mount_uploader :portrait, PortraitUploader

  validates :github, format: { with: /\Ahttps:\/\/github.com\//, message: "must be formatted as a URL starting with the text 'https://github.com/' followed by your username", allow_blank: true }
  validates :twitter, format: { with: /\Ahttps:\/\/twitter.com\//, message: "must be formatted as a URL starting with the text 'https://twitter.com/' followed by your username", allow_blank: true }
  validates :linkedin, format: { with: /www.linkedin.com\//, message: "must be formatted as a URL with the text 'www.linkedin.com/' followed by your personal URL", allow_blank: true }
  validates :email, presence:true, format: { with: /\w*@\w*\./, message: "must be a valid email address"}

  include Gravtastic
  gravtastic :secure => true, :size => 120

  def self.uniques(field)
  	self.uniq.pluck(field).delete_if{|x| x == ""}
  end

  def school_choices
  	School.find(:all, :order => "name ASC")
  end

  def filter_tags
  	filters = []
  	filters << schools.map {|school| school.name.parameterize }
  	filters << title.parameterize
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @people = Person.find(:all, :order => "last_name ASC")
  end

  def show
  end

  def new
  end

  def create
    if @person.save
      redirect_to @person, :notice => "Successfully created person."
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    # params.require(:transaction).permit(:name, school_ids => [])
    if @person.update_attributes(params[:person])
      redirect_to @person, :notice  => "Successfully updated person."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @person.destroy
    redirect_to people_url, :notice => "Successfully destroyed person."
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.haml
= form_for @person do |f|
  = render :partial => "layouts/error", :locals => {:error_message => f.error_messages}
  %p
    = f.label :first_name
    %br
    = f.text_field :first_name
  %p
    = f.label :last_name
    %br
    = f.text_field :last_name
  %p
    = f.label :title
    %br
    = f.text_field :title  
  %p
    = f.label :bio
    %br
    = f.text_field :bio
  %p
    = f.label :schools
    %br
    = collection_select(:person, :school_ids, School.find(:all, :order => "name ASC"), :id, :name, {prompt: true}, {:multiple => true})
  %p
    =f.label :portrait
    %br
    = image_tag @person.portrait_url(:thumb) if @person.portrait?
    %br
    =f.file_field :portrait
  %p
    = f.label :linkedin, "Linkedin URL"
    %br
    = f.text_field :linkedin
  %p
    = f.label :email, "Email Address"
    %br
    = f.text_field :email  
  %p
    = f.label :phone
    %br
    = f.text_field :phone
  %p
    = f.label :twitter, "Twitter URL"
    %br
    = f.text_field :twitter
  %p
    = f.label :github, "Github URL"
    %br
    = f.text_field :github
  %p
    = f.submit "Save", :class => "success-button"

app/views/people/edit.html.haml
- title "Edit Person"

%h1 Edit Person

= image_tag @person.gravatar_url(size: 128, default: 'identicon')

= render 'form'

%p
  = link_to "Show", @person, :class => "info-button"
  = link_to "View All", people_path, :class => "primary-button"

app/views/people/index.html.haml
- title "People"

%h1 People
%table
  %tr
    %th Photo
    %th First name
    %th Last name
    %th Title
    %th Email
  - for person in @people
    %tr
      %td= person.portrait? ? image_tag(person.portrait_url(:tiny)) : "None"
      %td= person.first_name
      %td= person.last_name
      %td= person.title
      %td= person.email
      %td= link_to 'Show', person, :class => "primary-button"
      -if can? :edit, person
        %td= link_to 'Edit', edit_person_path(person), :class => "info-button"
      -if can? :destroy, person
        %td= link_to 'Destroy', person, :confirm => 'Are you sure?', :method => :delete, :class => "danger-button"

-if can? :create, Person
  %p= link_to "New Person", new_person_path, :class => "success-button"

app/views/people/new.html.haml
- title "New Person"

%h1 New Person

= render 'form'

%p= link_to "Back to List", people_path

app/views/people/show.html.haml
- title "Person"

%h1 
  = @person.first_name
  = " "
  = @person.last_name
%p
  %strong Portrait:
  .preview-img
    = image_tag @person.portrait_url(:thumb) if @person.portrait?
    #{"None" if !@person.portrait?}
%p
  %strong Gravatar:
  %p
  = image_tag @person.gravatar_url(size: 128, default: 'wavatar')
%p
  %strong First Name:
  = @person.first_name
%p
  %strong Last Name:
  = @person.last_name
%p
  %strong Bio:
  = @person.bio
%p
  %strong Schools:
  %ul
  - for school in @person.schools
    %li= school.name
%p
  %strong Linkedin:
  = @person.linkedin
%p
  %strong Phone:
  = @person.phone
%p
  %strong Twitter URL:
  = @person.twitter
%p
  %strong Github:
  = @person.github
%p
  %strong Email:
  = @person.email

%p
  -if can? :edit, @person
    = link_to "Edit", edit_person_path(@person), :class => "info-button"
  -if can? :destroy, @person
    = link_to "Destroy", @person, :confirm => 'Are you sure?', :method => :delete, :class => "danger-button"
  = link_to "View All", people_path, :class => "primary-button"