config/routes.rb
OnPrem::Application.routes.draw do

  resources :pages

  resources :schools

  resources :slides

  resources :people

  resources :projects

  resources :users, only: :index

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks"}

  root to: "pages#home"

  match '/home' => 'pages#home'
  match '/offerings' => 'pages#offerings'
  match '/work' => 'pages#work'
  match '/team' => 'pages#team'
  match '/careers' => 'pages#careers'
  match '/contact' => 'pages#contact'
  match '/idc' => 'pages#idc'
  match '/about' => 'pages#about'
  
  

end

app/models/school.rb
# == Schema Information
#
# Table name: schools
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  icon       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class School < ActiveRecord::Base
  attr_accessible :name, :icon
  has_and_belongs_to_many :people
  mount_uploader :icon, ImageUploader
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def show
  end

  def new
  end

  def create
    if @school.save
      redirect_to @school, :notice => "Successfully created school."
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    if @school.update_attributes(params[:school])
      redirect_to @school, :notice  => "Successfully updated school."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @school.destroy
    redirect_to schools_url, :notice => "Successfully destroyed school."
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.haml
= form_for @school do |f|
  = render :partial => "layouts/error", :locals => {:error_message => f.error_messages}
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    =f.label :icon
    %br
    = image_tag @school.icon_url(:thumb) if @school.icon?
    %br
    =f.file_field :icon
  %p
    = f.submit "Save", :class => "success-button"

app/views/schools/edit.html.haml
- title "Edit School"

%h1 Edit School

= render 'form'

%p
  = link_to "Show", @school, :class => "info-button"
  = link_to "View All", schools_path, :class => "primary-button"

app/views/schools/index.html.haml
- title "Schools"

%h1 Schools

%table
  %tr
    %th Name
    %th Icon
  - for school in @schools
    %tr
      %td= school.name
      %td= image_tag school.icon_url(:tiny) if school.icon?
      %td= link_to 'Show', school, :class => "primary-button"
      -if can? :edit, school
        %td= link_to 'Edit', edit_school_path(school), :class => "info-button"
      -if can? :destroy, school
        %td= link_to 'Destroy', school, :confirm => 'Are you sure?', :method => :delete, :class => "danger-button"

-if can? :create, School
  %p= link_to "New School", new_school_path, :class => "success-button"

app/views/schools/new.html.haml
- title "New School"

%h1 New School

= render 'form'

%p= link_to "Back to List", schools_path

app/views/schools/show.html.haml
- title "School"

%h1= @school.name

%p
  %strong Name:
  = @school.name
%p
  %strong Icon:
  %br
  = image_tag @school.icon_url(:thumb) if @school.icon?

%p
  -if can? :edit, @school
    = link_to "Edit", edit_school_path(@school), :class => "info-button"
  -if can? :destroy, @school
    = link_to "Destroy", @school, :confirm => 'Are you sure?', :method => :delete, :class => "danger-button"
  = link_to "View All", schools_path, :class => "primary-button"