config/routes.rb
OnPrem::Application.routes.draw do

  resources :pages

  resources :schools

  resources :slides

  resources :people

  resources :projects

  resources :users, only: :index

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks"}

  root to: "pages#home"

  match '/home' => 'pages#home'
  match '/offerings' => 'pages#offerings'
  match '/work' => 'pages#work'
  match '/team' => 'pages#team'
  match '/careers' => 'pages#careers'
  match '/contact' => 'pages#contact'
  match '/idc' => 'pages#idc'
  match '/about' => 'pages#about'
  
  

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end

  def s3_static(image_name)
    "https://d2papxxk0j9ui4.cloudfront.net/static/#{image_name}"
  end
end

app/views/layouts/_error.html.haml
- if error_message
	.popup.popup-errors
		= error_message
		%button{:href => "#", :data => {:dismiss => "alert"}} Dismiss

app/views/layouts/_flash.html.haml
- unless flash.empty?
	.flash.popup.popup-success
		-flash.each do |name, msg|
			=content_tag :div, msg, id: "flash_#{name}"
		%button{:type => "button", :aria_hidden => "true", :data => {:dismiss => "alert"}} Dismiss

app/views/layouts/_navbar.html.haml
%nav#navbar{role: "navigation"}
  / Brand and toggle get grouped for better mobile display
  .container
    .header
      %button.toggle{"data-target" => "#nav-links", "data-toggle" => "collapse", type: "button"}
        / Bars that make up the toggle button icon
        %span
        %span
        %span
        %span
      %a.logo{href: "/"}
        %img{src: s3_static("OnPremLogoOnlySm.png"),alt:"OnPrem Logo Text Only", id: "logopic"}
        %img{src: s3_static("OnPremTextOnly.png"),alt:"OnPrem Logo Text Only", id: "logotext"}
    / Collect the nav links, forms, and other content for toggling
    #nav-links
      %ul.main-links
        = render "layouts/navlinks"
        - if can? :view, :people
          %li.dropdown
            %a.dropdown-toggle{href:"#", data:{toggle:"dropdown"}}
              %i.fa.fa-gear
              Admin 
              %b.caret
            %ul.dropdown-menu
              - if can? :view, :pages
                %li
                  = link_to "Pages", pages_path
              - if can? :view, :people
                %li
                  = link_to "People", people_path
              - if can? :view, :projects
                %li
                  = link_to "Projects", projects_path
              - if can? :view, :schools
                %li
                  = link_to "Schools", schools_path
              - if can? :view, :slides
                %li
                  = link_to "Slides", slides_path
              - if can? :view, :users
                %li
                  = link_to "Users", users_path
              %li
                = link_to "Sign Out", destroy_user_session_path, :method => :delete

app/views/layouts/_navlinks.html.haml
%li
  = link_to "About", "/about"
%li
  = link_to "Offerings", "/offerings"
%li
  = link_to "Work", "/work"
%li
  = link_to "Team", "/team"
%li
  = link_to "Careers", "/careers"
/ %li
/   = link_to "Innovation", "/idc"  
%li
  = link_to "Contact", "/contact"  

app/views/layouts/_social-icons.html.haml
.social-icons
  %ul
    / %li Find us on:
    %li
      %a{href: "https://twitter.com/OnPremSP", target: "_blank"}
        %span.icon
          %i.square-bg
          %i.twitter
    %li
      %a{href: "http://www.linkedin.com/company/onprem-solution-partners", target: "_blank"}
        %span.icon
          %i.square-bg
          %i.linkedin
    %li
      %a{href: "https://www.facebook.com/OnpremSolutionPartners", target: "_blank"}
        %span.icon
          %i.square-bg
          %i.facebook    
    %li
      %a{href: "http://instagram.com/onpremsp", target: "_blank"}
        %span.icon
          %i.square-bg
          %i.instagram

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title
			= h(yield(:title) || "OnPrem")

		= yield(:javascripts)

		%meta{content: "width=device-width,initial-scale=1.0", name: "viewport"}/

		/ %link{href: "http://fonts.googleapis.com/css?family=Roboto|Roboto+Condensed|Alegreya:700|Oswald:400|Droid+Serif:400,700italic|Rokkitt:700|Coustard:900|Bitter:900|Montserrat:400", rel: "stylesheet", type: "text/css"}/
		%link{href: "http://fonts.googleapis.com/css?family=Roboto|Roboto+Condensed|Fjalla+One", rel: "stylesheet", type: "text/css"}/

		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
	%body
		=render "layouts/navbar"
		- if controller_name != 'pages'
			.main
				.top-spacer
				= render :partial => "layouts/flash", :locals => {:flash => flash}
				= yield
		- else
			= render :partial => "layouts/flash", :locals => {:flash => flash}
			=yield
	.footer-container
		.footer
			.footer-logo
				%img{src: s3_static("OnPrem_Logo_White.png"), alt: "OnPrem Logo White"}
			.footer-nav
				%ul
					= render :partial => "layouts/navlinks"
					-if !signed_in?
						%li
							= link_to "Sign In", new_user_session_path
			%p
			.social
				= render :partial => "layouts/social-icons"
			%p
			.copyright
				%p &copy;2014 OnPrem Solution Partners, LLC

app/views/layouts/home.html.haml
!!!
%html

  %head
    %title
      = yield(:title) || "Untitled"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag "home"
    = javascript_include_tag "application"
    = csrf_meta_tag
    = yield(:head)

  %body
    #container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"

      - if show_title?
        %h1= yield(:title)

      = yield

app/views/layouts/not_home.html.haml
!!!
%html

  %head
    %title
      = yield(:title) || "Untitled"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag "home"
    = javascript_include_tag "application"
    = csrf_meta_tag
    = yield(:head)

  %body
    #container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"

      - if show_title?
        %h1= yield(:title)

      = yield

app/views/layouts/project.html.haml
%html

  %head
    %title
      = yield(:title) || "Untitled"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag "project"
    = javascript_include_tag :defaults
    = csrf_meta_tag
    = yield(:head)

  %body
    #container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"

      - if show_title?
        %h1= yield(:title)

      = yield